# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: One
    steps:
    - bash: touch adi
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: WebSite
  - job: secound
    dependsOn: One
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: WebSite
        downloadPath: $(System.DefaultWorkingDirectory)
    - bash: cat Website
    - bash: touch di && ls
